-- Primeiro, vamos renomear a tabela atual para itens_compra
ALTER TABLE historico_compras RENAME TO itens_compra;

-- Criar a tabela principal de compras
CREATE TABLE compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor VARCHAR NOT NULL,
    data_compra TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    tipo_compra VARCHAR NOT NULL DEFAULT 'fruta', -- 'fruta' ou 'outros'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL
);

-- Adicionar a coluna compra_id na tabela de itens
ALTER TABLE itens_compra 
ADD COLUMN compra_id BIGINT REFERENCES compras(id) ON DELETE CASCADE;

-- Criar índices para melhor performance
CREATE INDEX idx_compras_data ON compras(data_compra);
CREATE INDEX idx_itens_compra_id ON itens_compra(compra_id);

-- Trigger para atualizar o updated_at das compras
CREATE TRIGGER update_compras_updated_at
    BEFORE UPDATE ON compras
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column(); 