-- Create the historico_compras table
CREATE TABLE historico_compras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto VARCHAR NOT NULL,
    quantidade DECIMAL(10,2) NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    fornecedor VARCHAR NOT NULL,
    data_compra TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL,
    tipo_compra VARCHAR NOT NULL DEFAULT 'fruta', -- 'fruta' ou 'outros'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('UTC'::TEXT, NOW()) NOT NULL
);

-- Create an index on fornecedor and data_compra for faster queries
CREATE INDEX idx_historico_compras_fornecedor_data ON historico_compras(fornecedor, data_compra);

-- Create a function to update the updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('UTC'::TEXT, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create a trigger to automatically update the updated_at column
CREATE TRIGGER update_historico_compras_updated_at
    BEFORE UPDATE ON historico_compras
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column(); 