-- Create Operador table if it doesn't exist
CREATE TABLE IF NOT EXISTS "Operador" (
  id INTEGER PRIMARY KEY,
  parent_id INTEGER,
  name TEXT,
  last_name TEXT,
  username TEXT,
  email TEXT,
  phone TEXT,
  cpf TEXT,
  level INTEGER,
  is_profile BOOLEAN,
  profile_permission TEXT,
  image TEXT,
  image_key TEXT,
  full_name TEXT,
  should_update_at TIMESTAMP,
  pin_code TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  deleted_at TIMESTAMP,
  birthday DATE,
  gender INTEGER,
  scholarity TEXT,
  marital_status TEXT,
  atuation TEXT,
  courses TEXT,
  is_married BOOLEAN,
  cep TEXT,
  address TEXT,
  state TEXT,
  city TEXT,
  district TEXT,
  complement TEXT,
  ruc TEXT,
  distrito_py TEXT,
  user_twygo_id TEXT,
  magic_link_twygo TEXT,
  user_twygo_status BOOLEAN,
  expire_pin TIMESTAMP,
  password_confirmation TEXT,
  passwordExpireIn TIMESTAMP,
  first_access BOOLEAN,
  pin_phone TEXT
);

-- Create BalanceHistory table if it doesn't exist
CREATE TABLE IF NOT EXISTS "BalanceHistory" (
  id INTEGER PRIMARY KEY,
  cash_history_id INTEGER,
  store_sale INTEGER,
  total_sales INTEGER,
  total_sales_with_cpf INTEGER,
  total_sales_without_cpf INTEGER,
  total_percent_with_cpf NUMERIC,
  total_percent_without_cpf NUMERIC,
  delivery_sale INTEGER,
  total NUMERIC,
  total_store NUMERIC,
  total_delivery NUMERIC,
  total_ifood NUMERIC,
  total_app NUMERIC,
  total_others NUMERIC,
  money NUMERIC,
  credit_card NUMERIC,
  debit_card NUMERIC,
  online NUMERIC,
  pix NUMERIC,
  ticket NUMERIC,
  change_amount NUMERIC,
  created_at TIMESTAMP,
  deleted_at TIMESTAMP,
  qr_code TEXT
);

-- Create Caixa table if it doesn't exist
CREATE TABLE IF NOT EXISTS "Caixa" (
  id INTEGER PRIMARY KEY,
  cash_id INTEGER,
  cash INTEGER,
  store_id INTEGER,
  backup_url TEXT,
  opened_at TIMESTAMP,
  opened_by INTEGER REFERENCES "Operador"(id),
  amount_on_open NUMERIC,
  closed_at TIMESTAMP,
  closed_by INTEGER REFERENCES "Operador"(id),
  amount_on_close NUMERIC,
  amount_on_cash NUMERIC,
  in_result NUMERIC,
  out_result NUMERIC,
  result_cash NUMERIC,
  observation TEXT,
  created_at TIMESTAMP,
  deleted_at TIMESTAMP,
  balance_history_id INTEGER REFERENCES "BalanceHistory"(id),
  usd_exchange_rate NUMERIC,
  ars_exchange_rate NUMERIC,
  pyg_exchange_rate NUMERIC,
  local_opened_at TIMESTAMP,
  local_closed_at TIMESTAMP
);

-- Add foreign key constraints
ALTER TABLE "BalanceHistory"
  ADD CONSTRAINT fk_balancehistory_caixa
  FOREIGN KEY (cash_history_id) REFERENCES "Caixa"(id); 